apiVersion: v1
kind: Secret
metadata:
  name: redis-auth
  namespace: redis-ha
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: database
type: Opaque
stringData:
  password: "sentry"
